# Generated by Django 3.1.6 on 2021-04-18 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_tian'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceshi',
            options={},
        ),
        migrations.AlterModelTable(
            name='tian',
            table='tian',
        ),
    ]
