# Generated by Django 3.1.6 on 2021-04-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_tian1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tian1',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
