# Generated by Django 3.1.6 on 2021-04-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20210421_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tian1',
            options={'ordering': ['-c_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='tian1',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tian1',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
