# Generated by Django 3.1.6 on 2021-04-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20210423_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='tian1',
            name='has_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
